name = "muscat-email-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "muscat-db"
database_id = "local"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "muscat-attachments"
